In [ ]:
#!uv add numpy

In [1]:
import numpy as np
print(np.__version__)

2.5.1


In [3]:
!uv pip list | findstr numpy

numpy                   2.5.1


In [5]:
# python을 이용한 계산
%time sum(range(1000000))

CPU times: total: 0 ns
Wall time: 12.2 ms


499999500000

In [6]:
# numpy을 이용한 계산
%time np.sum(np.arange(1000000))

CPU times: total: 0 ns
Wall time: 9.64 ms


np.int64(499999500000)

In [7]:
# 2행 3열의 수치형 2차원 배열 정의
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("배열의 차원:", arr.ndim, np.ndim(arr))   # 출력: 2   2
print("배열의 형태:", arr.shape, np.shape(arr))  # 출력: (2, 3) (2, 3)
print("원소 총 개수:", arr.size, np.size(arr))  # 출력: 6 6
print("데이터 타입:", arr.dtype)  # 출력: int64

# 정수형 데이터를 실수형(Float) 데이터 타입으로 강제 변환
float_arr = arr.astype(np.float64)
print("변경된 타입:", float_arr.dtype)  # 출력: float64

배열의 차원: 2 2
배열의 형태: (2, 3) (2, 3)
원소 총 개수: 6 6
데이터 타입: int64
변경된 타입: float64


In [8]:
a = np.array([1, 2, 3])
print(type(a))            # <class 'numpy.ndarray'>
print(a.dtype)            # int64 : 정수 64bit => 8byte

<class 'numpy.ndarray'>
int64


In [9]:
int64_a = np.array([1, 2, 3])
print(int64_a.dtype )   # int64
float32_b = int64_a.astype(np.float32)
print(float32_b )                 # [1., 2., 3.]
print(float32_b .dtype)           # float32

int64
[1. 2. 3.]
float32


### np.array(리스트)

In [10]:
# 1차원 배열 = 벡터
a = np.array([1,2,3])
print(a)           # [1 2 3]
print(dir(a))
print(type(a))     # <class 'numpy.ndarray'>
print(a.shape)     # (3,)

[1 2 3]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '_

In [11]:
# 2차원 배열 = 행렬
b = np.array([[1,2],[3,4]]) # 2행 2열
print(b)                # [[1 2][3 4]]
print(dir(b))
print(type(b))           # <class 'numpy.ndarray'>
print(b.shape)           # (2, 2)

[[1 2]
 [3 4]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd

In [13]:
# 3차원 배열 = 텐서(tensor)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 2층(공간, 면), 2행 , 2열
print(c)          # [[[1,2][3,4]]  
                   #  [[5,6][7,8]]]
print(dir(c))
print(type(c))     # <class 'numpy.ndarray'>
print(c.shape)     # (2, 2, 2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__

In [14]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
# numpy는 homogeneous 즉 같은 데이터 타입만 저장 할 수 있다.
a = np.array([1, '2', 3])
print(a)             # ['1' '2' '3']

['1' '2' '3']


In [15]:
a = np.array(['a', 1, True])
print(a)              # array(['a', '1', 'True'], dtype='<U21')

['a' '1' 'True']


In [16]:
a = np.array([True, False, True])
print(a)               # array([ True, False,  True])

[ True False  True]


In [17]:
a = np.array([True, False, True, 0, 1]) # False -> 0, True -> 1
print(a)                 #  array([1, 0, 1, 0, 1])

[1 0 1 0 1]


### np.zeros((행, 열))

In [20]:
a =  np.zeros(3)
print(a)

a = np.zeros((2,3))
print(a)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


#### np.ones(x)
- 1로 채움

In [21]:
# np.ones(x)
a = np.ones(3)
print(a)

[1. 1. 1.]


In [22]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


#### np.eye(x,y,k)
단위행렬
대각선 값 1, 나머지 0

In [23]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# 3행 2열의  단위 행렬 생성
a = np.eye(3, 2) # 3행 2열
print(a)                 # [[1. 0.][0. 1.][0. 0.]]

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [ ]:
# 1를 시작되는 위치를 지정할 수 있다. (k=1)
a = np.eye(3, 4, k=1) # 3행 4열
print(a)                 # [[0. 1. 0. 0.]
                        #   [0. 0. 1. 0.]
                        # [0. 0. 0. 1.]]

#### identity(x)
-  크기 한 개만 지정해서 생성

In [25]:
a = np.identity(3)
print(a)                #[[1. 0. 0.]
                        #[0. 1. 0.]
                        #[0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### np.full((행,열), 값)

In [26]:
a = np.full((2,2), 1)       # np.full(shape, fill_value)
print(a)                    # [[1 1][1 1]]

[[1 1]
 [1 1]]


In [27]:
a = np.full((2,2), [1, 2])  # np.full(shape, fill_value)
print(a)                   # [[1 2][1 2]]

[[1 2]
 [1 2]]


In [28]:
a = np.full((2,2), [[1],[2]])  # np.full(shape, fill_value)
print(a)                    # [[1 1][2 2]]

[[1 1]
 [2 2]]


In [29]:
a = np.full((2,2), [[1,2],[3,4]])  # np.full(shape, fill_value)
print(a)                     # [[1 2][3 4]]

[[1 2]
 [3 4]]


#### np.empty((행, 열))
- 배열을 생성하고 초기화를 지정하지 않는다.
- 메모리에 있는 값이나 이전에 사용했던 값들로 채워진다.

In [30]:
a = np.empty(3)
print(a)

[1. 1. 1.]


In [31]:
a = np.empty((2,3))
print(a)            #[[1. 0. 0.]
                    #[1. 0. 0.]]

[[1. 0. 0.]
 [1. 0. 0.]]


#### linspace
- 동등한 간격으로 값을 생성한다.
- 0부터 49까지 50개가 생성된다면 세 번째 num인자 값이 생략되여 있으므로 start와 end 계산해서 default 50이 생성된다.
- linspace(start, end, num)
- linspace (0, 49) #num의 default value 50

In [32]:
a = np.linspace(0, 49)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


In [33]:
a = np.linspace(0, 5)
print(a)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [34]:
# endpoint=False로 설정하면 5가 포함이 안된다.
a = np.linspace(0, 5, endpoint=False)
print(a)            # [0.   0.1  0.2 ..  4.7, 4.8  4.9]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]


#### logspace
- linspace과 비슷하다.
- log scale을 사용하는 차이가 있다.
- 1부터 50까지 사이의 10개의 요소를 생성한다.

In [35]:
a = np.logspace(1, 50)
print(a)            # [1.e+01 1.e+02 1.e+03,...,1.e+48 1.e+49 1.e+50]

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10
 1.e+11 1.e+12 1.e+13 1.e+14 1.e+15 1.e+16 1.e+17 1.e+18 1.e+19 1.e+20
 1.e+21 1.e+22 1.e+23 1.e+24 1.e+25 1.e+26 1.e+27 1.e+28 1.e+29 1.e+30
 1.e+31 1.e+32 1.e+33 1.e+34 1.e+35 1.e+36 1.e+37 1.e+38 1.e+39 1.e+40
 1.e+41 1.e+42 1.e+43 1.e+44 1.e+45 1.e+46 1.e+47 1.e+48 1.e+49 1.e+50]


In [36]:
a = np.logspace(1, 50, 10)
print(a)              # [1.00000000e+01 ... 1.00000000e+50

[1.00000000e+01 2.78255940e+06 7.74263683e+11 2.15443469e+17
 5.99484250e+22 1.66810054e+28 4.64158883e+33 1.29154967e+39
 3.59381366e+44 1.00000000e+50]


#### arange
np.arange([**start**, ]stop, [step, ]dtype=**None**)

- start: 생성할 배열의 시작 값 (기본값은 0)
- stop: 생성할 배열의 종료 값 (이 값은 포함되지 않음)
- step: 숫자 사이의 간격 (기본값은 1)
- dtype: 생성할 배열의 데이터 타입 (옵션)

In [37]:
# 기본 사용법
# 0부터 9까지의 숫자 배열 생성
arr = np.arange(10)
print(arr)              # [0 1 2 3 4 5 6 7 8 9]


# 시작 값과 종료 값 설정
arr = np.arange(3, 10)  # 3부터 9까지
print(arr)              # [3 4 5 6 7 8 9]


# 간격 설정
arr = np.arange(1, 10, 2)  # 1부터 9까지 2씩 증가
print(arr)                 # [1 3 5 7 9]


# 실수 간격 사용
arr = np.arange(0, 1, 0.1)  # 0부터 1까지 0.1씩 증가
print(arr)  # [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[1 3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### _like
- _like가 붙으면 shape이 같게 만들어진다.
- 연산하기 위해서 shape을 맞춰야 하는 경우가 있다.

In [39]:

a = np.array([[1,2,3],[4,5,6]])
print(a)

b = np.ones_like(a) # a배열의 shape을 복사한다.
print(b)


# [[1 2 3]
#  [4 5 6]]
# [[1 1 1]
#  [1 1 1]]


[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]


In [40]:
a = np.array([[1.,2.,3.],[4.,5.,6.]])
print(a)

b = np.ones_like(a) # a배열의 shape을 복사한다.
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [42]:
a = np.array([[1.,2.,3.],[4.,5.,6.]])
print(a)

b = np.zeros_like(a)
print(b)


# [[1. 2. 3.]
#  [4. 5. 6.]]
# [[0. 0. 0.]
#  [0. 0. 0.]]


[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [43]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [44]:
help(np.array)

Help on built-in function array in module numpy:

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, ndmax=0, like=None)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          ndmax=0, like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or i

## copy

#### python copy

In [45]:
a = [1, 2, 3]        # list
b = a
print(b)
print(a is b )        # 메모리 주소 비교 True
b[0] = 7
print(a)               # [7, 2, 3]           
print(b)                # [7, 2, 3]

[1, 2, 3]
True
[7, 2, 3]
[7, 2, 3]


### 인덱싱

In [46]:
# Boolean Indexing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

#불리언 인덱싱: 5보다 큰 데이터만 필터링
print(arr[arr>5])       # [6 7 8 9]

[6 7 8 9]


In [47]:
arr = np.array([
    [0, 1, 2, 3],
    [4, 5, 6,7],
    [8, 9, 10, 11]
])

axis_ABC = ['A', 'A', 'B', 'C', 'C']

bool_mask = arr[axis_ABC == 'A']
print(arr[bool_mask])  # 출력: [[0,1,2,3], [4,5,6,7]]

[]


팬시 인덱싱 (Fancy Indexing)

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[[0, 2]])     # 출력: [[1, 2, 3], [7, 8, 9]]

#### 팬시 인덱싱: 0번 행과 2번 행만 선택하여 추출
- 슬라이싱 불가, 비연속 적이라

In [51]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11],
    [12, 13, 14]
])

# print(arr[[1:3]])       #오류!!!

print(arr[[1, 2]])     # [[3, 4,5], [6, 7, 8]]

print(arr[[-1, -2]])    # [[12, 13, 14], [9, 10, 11]]

[[3 4 5]
 [6 7 8]]
[[12 13 14]
 [ 9 10 11]]


팬시 인덱싱과 불리언 차이

In [88]:
a = np.arange(24).reshape(2,3,4) # 3차원(2층(면, 공간), 3행, 4열)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [89]:
# indexing은 차원이 하나 감소해서 가져온다. (3차원을 2차원으로 가져온다.)
a[0]


# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
# fancy indexing은 원래 3차원 그대로 가져온다.
a[[0]]


# array([[[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7],
#         [ 8,  9, 10, 11]]])


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

ellipsis

In [91]:
a[0]=a[0, :, :]=a[0,...]
print(a[0])  # indexing 기법
print(a[0, :, :]) # slicing 기법
print(a[0,...])  # ellipsis 기법(생략기법)


# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [92]:
type(...)

ellipsis

In [93]:
a[[0], :, :] # b[[0]]은  b[[0], :, :]의 단축 표현이다.

# array([[[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7],
#         [ 8,  9, 10, 11]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [100]:
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [102]:
a[0, :, 1] 

array([1, 5, 9])

In [103]:
a[[0],:, [1]]

array([[1, 5, 9]])

In [96]:
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
print(a[0, :, 1])        # array([1, 5, 9])

print(a[[0],:, [1]])     # array([[1, 5, 9]])



[[1 5 9]]


In [60]:
# 숫자 1, 5, 9, 3, 7, 11가져오기
print(a[0, :, 1])              # [1 5 9]

[1 5 9]


In [61]:
a[[0], :, [1]]                 # array([[1, 5, 9]])


array([[1, 5, 9]])

In [62]:
# 숫자 1,5,9,3,7,11 가져오기
a[[0], :, [1,3]]
# array([[ 1,  5,  9],
#        [ 3,  7, 11]])

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [72]:
b = a[:,[1],:]
b.shape

(2, 1, 4)

In [64]:
# 숫자 4,5,6,7,16,17,18,19 가져오기
a[:, 1, :]
# array([[ 4,  5,  6,  7],
#        [16, 17, 18, 19]])

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [65]:
a[:, [1], :]

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [66]:
# 숫자 3,7,11,15,19,23 가져오기
a[:, :, 3]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [67]:
a[:, :, [3]]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [68]:
a[:, :, -1]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [69]:
a[..., -1]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [70]:
a[..., 3]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [71]:
a[..., 3:4]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

줄임표현 ... 이랑은 다름

In [73]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999], shape=(10000,))

In [74]:
# ... 양쪽으로 출력 갯수 지정
np.set_printoptions(edgeitems=6)

np.arange(10000)

array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
       9998, 9999], shape=(10000,))

## 배열의 형태 변형 (Reshaping)

In [ ]:
arr = np.array([[1, 2], [3, 4]])

dap = arr.flatten()
print(dap)                      # 출력 : [1 2 3 4]


# 메모리 공유 확인:: False
print(f'메모리 공유 확인:: {np.shares_memory(arr, dap)}')     #False
print(f' {arr is dap}')     #False
# is는 메모리 같아도 배열 모양 다르면 False
# shares_memory()는 모양 달라도 메모리 공간 같으면 True


[1 2 3 4]
메모리 공유 확인:: False
 False


In [81]:
# 1차원 12개 원소 배열을 3행 4열 2차원 배열로 변경
arr_1d = np.arange(12)
arr_2d = arr_1d.reshape(3, 4)

# 메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_1d ,arr_2d)}') #True


# 행의 크기는 2로 지정하고, 열의 크기는 자동 계산(-1)하여 배치
arr_auto = arr_1d.reshape(2, -1)  # 결과적으로 2행 6열로 자동 변환됨

# 메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_1d,arr_auto)}')    #True

arr_2d = arr_1d.reshape(3, 4)
arr_line= np.ravel(arr_2d)

# [ 0  1  2  3  4  5  6  7  8  9 10 11]
print(arr_line)

#메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_2d, arr_line)}')   #True
print(arr_1d is arr_2d)     #False(모양 다름)

메모리 공유 확인:: True
메모리 공유 확인:: True
[ 0  1  2  3  4  5  6  7  8  9 10 11]
메모리 공유 확인:: True
False


### 배열 결합 및 분할

2차원 이상

In [82]:
a = np.array([[1, 2, 3]])
print(f'a={a}')                                # a=[[1 2 3]]

b = np.array([[4, 5, 6]])
print(f'b={b}')                                # b=[[4 5 6]]

print(np.r_[a,b])                              # [[1 2 3]           [4 5 6]]

v_row = np.vstack([a,b])
print(f'v_row:: {v_row}')                      # v_row:: [[1 2 3][4 5 6]]

concat_row = np.concatenate((a, b), axis=0)    # axis = 0
print(f'concat_row:: {concat_row}')            # concat_row:: [[1 2 3][4 5 6]]

a=[[1 2 3]]
b=[[4 5 6]]
[[1 2 3]
 [4 5 6]]
v_row:: [[1 2 3]
 [4 5 6]]
concat_row:: [[1 2 3]
 [4 5 6]]


In [83]:
a = np.array([[1, 2, 3]])
print(f'a={a}')                                # a=[[1 2 3]]

b = np.array([[4, 5, 6]])
print(f'b={b}')                                # b=[[4 5 6]]

print(np.c_[a,b])                              # [[1 2 3 4 5 6]]

h_col = np.hstack([a,b])
print(f'h_col:: {h_col}')                      # h_col:: [[1 2 3 4 5 6]]

concat_col = np.concatenate((a, b), axis=1)    # axis = 1
print(f'concat_col:: {concat_col}')            # concat_col:: [[1 2 3 4 5 6]]

a=[[1 2 3]]
b=[[4 5 6]]
[[1 2 3 4 5 6]]
h_col:: [[1 2 3 4 5 6]]
concat_col:: [[1 2 3 4 5 6]]


1차원

In [105]:
a = np.array([1, 2, 3])
print(f'a={a}')           # a=[1 2 3]      

b = np.array([4, 5, 6])
print(f'b={b}')           # b=[4 5 6]

print(np.r_[a,b])

v_row = np.vstack([a,b])
print(f'h_row:: {v_row}')     # v_row:: [[1 2 3][4 5 6]]

concat_row = np.concatenate((a, b), axis=0)  # axis = 0
print(f'concat_row:: {concat_row}') # concat_row:: [1 2 3 4 5 6]

a=[1 2 3]
b=[4 5 6]
[1 2 3 4 5 6]
h_row:: [[1 2 3]
 [4 5 6]]
concat_row:: [1 2 3 4 5 6]


In [ ]:
a = np.array([1, 2, 3])
print(f'a={a}')                                # a=[1 2 3]

b = np.array([4, 5, 6])
print(f'b={b}')                                # b=[4 5 6]

print(np.c_[a,b])                              # [[1 4]
                                                #[2 5]
                                                # [3 6]]

h_col = np.hstack([a,b])
print(f'h_col:: {h_col}')                      # h_col:: [1 2 3 4 5 6]

# AxisError: axis 1 is out of bounds for array of dimension 1
concat_col = np.concatenate((a, b), axis=1)    # axis = 1        #오류

a=[1 2 3]
b=[4 5 6]
[[1 4]
 [2 5]
 [3 6]]
h_col:: [1 2 3 4 5 6]


AxisError: axis 1 is out of bounds for array of dimension 1

In [107]:
a = np.arange(12).reshape(3,4)
print(a)
x, y = np.split(a, 2, axis = 1)
print(x)
print(y)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [108]:
# 2차원이면 3차원으로 증가한다.
b = np.stack((x,y), axis = 0)
print(b.shape) # 2차원(m, n) => 3차원(2, m, n)
print(b)

(2, 3, 2)
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[ 2  3]
  [ 6  7]
  [10 11]]]


In [110]:
print(b)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [111]:
print(x)
print(y)

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [109]:
b = np.stack((x,y), axis = 1)
print(b.shape) # 2차원(m, n) => 3차원(m,2, n)
print(b)

(3, 2, 2)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [113]:
print(x)
print(y)

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [112]:
c = np.concatenate((x, y), axis=0)
print(c.shape)
print(c)

(6, 2)
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [ 2  3]
 [ 6  7]
 [10 11]]


In [114]:
c = np.concatenate((x, y), axis=1)
print(c.shape)
print(c)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### 배열 분할하기

In [117]:
x = np.arange(18)
print(f'x::{x}')

x = x.reshape(-1, 6)
print(f'x::{x}')

x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [122]:
print(np.hsplit(x, 3))
print(np.hsplit(x, (2,4)))

[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


In [123]:
print(np.split(x, 3, axis=1))
print(np.split(x, (2, 4), axis=1))

[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


In [119]:
x = np.arange(18)
print(f'x::{x}')

x = x.reshape(-1, 6)
print(f'x::{x}')

x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [120]:
print(np.vsplit(x, 3))
print(np.vsplit(x, (1,2)))

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]


In [121]:

print(np.split(x, 3, axis=0))
print(np.split(x, (1, 2), axis=0))

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]


#### 배열의 차원 확장 및 축소

차원확장

- 기존 데이터는 유지하면서 새로운 축(Axis)을 추가해 차원을 늘리는 방법입니다. (예: $1D \rightarrow 2D$, $2D \rightarrow 3D$)
- ① np.newaxis (슬라이싱 기법)
가장 많이 사용되는 직관적인 방식입니다. 원하는 축 위치에 np.newaxis를 넣어 새로운 차원을 만든다.

In [126]:
arr = np.array([1, 2, 3]) # shape: (3,)

# 행 방향(axis 0) 확장 -> shape: (1, 3)
row_vec = arr[np.newaxis, :]

row_vec

array([[1, 2, 3]])

In [127]:
# 열 방향(axis 1) 확장 -> shape: (3, 1)
col_vec = arr[:, np.newaxis]

print("행벡터:\n", row_vec)
print("열벡터:\n", col_vec)

행벡터:
 [[1 2 3]]
열벡터:
 [[1]
 [2]
 [3]]


In [129]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


np.newsaxis 대신에 None을 써도 된다.

None은 직관적이지 않고 헤갈려서 np.newaxis를 제공한다.

In [130]:
b = a[:,:,None]
print(b.shape)
print(b)

(3, 4, 1)
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]


- ② `np.expand_dims(a, axis)`

명시적으로 지정한 `axis` 위치에 차원을 1개 추가한다.

In [131]:
import numpy as np

arr = np.array([1, 2, 3]) # shape: (3,)

# axis=0 위치에 차원 추가 -> shape: (1, 3)
e0 = np.expand_dims(arr, axis=0)

# axis=1 위치에 차원 추가 -> shape: (3, 1)
e1 = np.expand_dims(arr, axis=1)

print("e0.shape:", e0.shape) # (1, 3)
print("e1.shape:", e1.shape) # (3, 1)

e0.shape: (1, 3)
e1.shape: (3, 1)


#### 차원 축소

- 1. np.squeeze(a, axis=None)

In [132]:
import numpy as np

# shape: (1, 3, 1) 인 3차원 배열
arr_3d = np.array([[[1], [2], [3]]])

# 크기가 1인 모든 차원 축소 -> shape: (3,)
squeezed = np.squeeze(arr_3d)

print("원래 shape:", arr_3d.shape) # (1, 3, 1)
print("축소 후 shape:", squeezed.shape) # (3,)
print("결과:", squeezed) # [1 2 3]

원래 shape: (1, 3, 1)
축소 후 shape: (3,)
결과: [1 2 3]


2. ravel()/ flatten() / reshape(-1) (평탄화: 1차원 변환)

다차원 배열을 **1차원 배열로 완전히 펼칠 때** 사용합니다.

- `ravel()`: 원본의 뷰(View)를 반환 (메모리 절약, 속도 빠름)
- `flatten()`: 원본을 복사(Copy)하여 반환
- `reshape(-1)`: 가장 범용적인 평탄화 방식

In [133]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]]) # shape: (2, 2)

# 모두 1차원 배열 [1, 2, 3, 4] (shape: (4,))로 변환
r_arr = matrix.ravel()
f_arr = matrix.flatten()
re_arr = matrix.reshape(-1)

print("1차원 평탄화 결과:", r_arr) # [1 2 3 4]

1차원 평탄화 결과: [1 2 3 4]


In [134]:
a = np.arange(24).reshape(2,3,4)
print(a)

print(a[0, :, 1])        # array([1, 5, 9])

print(a[[0],:, [1]])     # array([[1, 5, 9]])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[1 5 9]
[[1 5 9]]


## 선형대수 기초

In [135]:
# 1. 벡터 및 행렬 생성
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

In [137]:
# 2. 벡터 내적 (Dot Product)
dot_product = np.dot(v1, v2)
print("Vector Dot Product:")
print(dot_product)
# 출력: 32 (1*4 + 2*5 + 3*6)

Vector Dot Product:
32


In [138]:
# 3. 행렬 곱셈 (Matrix Multiplication)
matrix_mul = np.matmul(A, B) # 또는 A @ B
print("\nMatrix Multiplication (A @ B):")
print(matrix_mul)
# 출력:
# [[19 22]
#  [43 50]]


Matrix Multiplication (A @ B):
[[19 22]
 [43 50]]


In [139]:
# 4. 전치 행렬 (Transpose Matrix)
A_transpose = A.T
print("\nTranspose of Matrix A:")
print(A_transpose)
# 출력:
# [[1 3]
#  [2 4]]


Transpose of Matrix A:
[[1 3]
 [2 4]]


In [140]:
# 5. 역행렬 (Inverse Matrix)
A_inv = np.linalg.inv(A)
print("\nInverse of Matrix A:")
print(A_inv)
# 출력:
# [[-2.   1. ]
#  [ 1.5 -0.5]]

# 6. 행렬식 (Determinant)
det_A = np.linalg.det(A)
print("\nDeterminant of Matrix A:")
print(det_A)
# 출력: -2.0 (1*4 - 2*3)

# 7. 고유값 및 고유벡터 (Eigenvalues & Eigenvectors)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of A:")
print(eigenvalues)
# 출력: [-0.37228132  5.37228132]

print("\nEigenvectors of A:")
print(eigenvectors)
# 출력:
# [[-0.82456484 -0.41597356]
#  [ 0.56576746 -0.90937671]]


Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of Matrix A:
-2.0000000000000004

Eigenvalues of A:
[-0.37228132+0.j  5.37228132+0.j]

Eigenvectors of A:
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]


## **종합 미니 프로젝트 (실전 실습)**:

[예시 1] NumPy만으로 가상의 학생 성적 데이터셋 생성, 평균/표준편차 구하기, 낙제점 수정하기

학생 5명의 3개 과목(국어, 영어, 수학) 성적 데이터를 생성하고, 통계량 계산 및 기준 이하 점수(낙제점)를 수정하는 전처리 과정이다.

In [141]:
import numpy as np

# 1. 시드 고정 및 가상의 학생 성적 데이터셋 생성 (학생 5명, 과목 3개)
np.random.seed(42)
scores = np.random.randint(40, 101, size=(5, 3))

print("1. 원본 성적 데이터셋 (5명 x 3과목):")
print(scores)

# 2. 각 과목별 평균 및 표준편차 구하기 (axis=0: 세로/열 방향 연산)
subject_mean = np.mean(scores, axis=0)
subject_std = np.std(scores, axis=0)

print("\n2. 과목별 평균:")
print(subject_mean)

print("\n3. 과목별 표준편차:")
print(np.round(subject_std, 2))

# 3. 각 학생별 평균 구하기 (axis=1: 가로/행 방향 연산)
student_mean = np.mean(scores, axis=1)

print("\n4. 학생별 평균 점수:")
print(np.round(student_mean, 2))

# 4. 낙제점 수정하기 (60점 미만인 점수를 60점으로 일괄 수정)
# np.where(조건, 참일 때 값, 거짓일 때 값) 활용
fixed_scores = np.where(scores < 60, 60, scores)

print("\n5. 낙제점(60점 미만) 수정 후 데이터셋:")
print(fixed_scores)

1. 원본 성적 데이터셋 (5명 x 3과목):
[[ 78  91  68]
 [ 54  82  47]
 [100  60  78]
 [ 97  58  62]
 [ 50  50  63]]

2. 과목별 평균:
[75.8 68.2 63.6]

3. 과목별 표준편차:
[20.88 15.57 10.05]

4. 학생별 평균 점수:
[79.   61.   79.33 72.33 54.33]

5. 낙제점(60점 미만) 수정 후 데이터셋:
[[ 78  91  68]
 [ 60  82  60]
 [100  60  78]
 [ 97  60  62]
 [ 60  60  63]]


[예시 2] 단순 이미지 픽셀 데이터(3차원 배열)를 불러와 흑백 전환 및 크기 조절 전처리 구현

$(H, W, C)$ 구조의 3차원 RGB 이미지 데이터를 생성하여 표준 공식을 통한 흑백(Grayscale) 전환 및 다운샘플링(크기 조절)을 구현하는 코드이다.

In [142]:
import numpy as np

# 1. 가상의 RGB 이미지 픽셀 데이터 생성 (높이 4 x 너비 4 x 채널 3)
np.random.seed(100)
image_rgb = np.random.randint(0, 256, size=(4, 4, 3), dtype=np.uint8)

print("1. 원본 RGB 이미지 Shape:")
print(image_rgb.shape)

# 2. RGB 흑백 전환 (Grayscale Conversion)
# ITU-R BT.601 표준 공식: Y = 0.299*R + 0.587*G + 0.114*B
# 채널 축(axis 2)에 가중치를 내적(Dot Product)하거나 브로드캐스팅하여 계산함
weights = np.array([0.299, 0.587, 0.114])
image_gray = np.dot(image_rgb, weights).astype(np.uint8)

print("\n2. 흑백 전환 후 이미지 Shape:")
print(image_gray.shape)  # (4, 4)로 차원 축소됨

print("\n3. 흑백 이미지 픽셀 값:")
print(image_gray)

# 3. 이미지 크기 조절 (Downsampling / Resizing)
# 슬라이싱([::2, ::2])을 이용하여 가로/세로 픽셀을 2칸씩 스킵함으로써 크기를 1/2로 줄임
image_resized = image_gray[::2, ::2]

print("\n4. 크기 조절(2x2로 축소) 후 이미지 Shape:")
print(image_resized.shape)

print("\n5. 최종 축소된 이미지 픽셀 값:")
print(image_resized)

1. 원본 RGB 이미지 Shape:
(4, 4, 3)

2. 흑백 전환 후 이미지 Shape:
(4, 4)

3. 흑백 이미지 픽셀 값:
[[ 93  80 170  63]
 [175  87 124 128]
 [ 97 173  36  50]
 [ 89  73  33 139]]

4. 크기 조절(2x2로 축소) 후 이미지 Shape:
(2, 2)

5. 최종 축소된 이미지 픽셀 값:
[[ 93 170]
 [ 97  36]]
